### ISSUE TITLE
PyTorch compatibility for older version of Mac

### ISSUE THREAD

**Issue by muratti18462** [simon-muenker/cltrier_nlp#1]
While I was trying to run this notebook, 0.2--Encoder-Basics,  I run into this error, 

Cell 7 line 1 -----
 encoder = nlp.encoder.Encoder()
 pooler = nlp.encoder.EncoderPooler()

AttributeError: module 'cltrier_nlp' has no attribute 'encoder' .

I also try to install the newest version of the cltrier_nlp library, pip install cltrier_nlp==0.1.3 , it throws this error, 

ERROR: Could not find a version that satisfies the requirement torch<3.0.0,>=2.3.0 (from cltrier-nlp) (from versions: 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch<3.0.0,>=2.3.0

I am using intel MacBook.

<img width="1150" alt="Screenshot 2024-05-02 at 13 36 05" src="https://github.com/simon-muenker/cltrier_nlp/assets/55508480/782cb455-b5b5-4c00-a802-e799e116e794">

**Comment by simon-muenker** [comment]
Thanks for reporting it. I deployed a fix that drops the required versions to `torch==2.2.2`. Install the newest version of our package: `pip install cltrier_nlp==0.1.5`

Please confirm the fix, then I’ll close this issue.
